
import '../../../../../constants/image_strings.dart';

class UflEmployeeBdayList {

  static const List<String> allEmployeeName = [
      'PC Jha',
  'Naveen Kumar',
  'Prithyul Singh Anand',
  'Prince Kumar Singh',
  'Ritik Sharma',
  'Brij Bihari Bansal',
  'Jai Lama',
  'Shailesh Kumar',
  'Vishal Mehta',
  'Pradeep Kumar',
  'Shivani Chugh',
  'Arun Kumar',
  'Varun Sharma',
  'Sonal',
  'Sudarshan Singh',
  'Rajesh Bisht',
  'Asadullah Johar',
  'Pooja',
  'Jas Karan Singh',
  'Shailesh Sharma',
  'Gurjinder Singh',
  'Amit Raghav',
  'Kapil Ji',
  'Rahul Kashyap',
  'Vinay Kumar',
  'Asheesh Singhal',
  'Parul Kumar Bhatia',
  'Sharad Sharma',
  'Raj Kishore Sharma',
  'Nitesh kumar',
  'Narender',
  'Amit Kumar Singh',
  'Rakhi Jha',
  'Sonu Singh',
  'Shikha Sharma',
  'Taufique Anwar',
  'Karunakar Ji',
  'Rajeev Kumar Jha',
  'Sonam',
  'Upender Ji',
  'Rajeev Kumar Sachdeva',
  ];

  static const List<String> birthDate = [
    'January 02, 2024',
    'January 09, 2024',
    'January 20, 2024',
    'February 09, 2024',
    'February 17, 2024',
    'March 01, 2024',
    'March 22, 2024',
    'March 25, 2024',
    'March 30, 2024',
    'April 02, 2024',
    'April 02, 2024',
    'April 07, 2024',
    'April 07, 2024',
    'April 21, 2024',
    'April 26, 2024',
    'May 01, 2024',
    'May 05, 2024',
    'May 15, 2024',
    'June 03, 2024',
    'June 29, 2024',
    'July 03, 2024',
    'July 10, 2024',
    'July 31, 2024',
    'August 02, 2024',
    'August 16, 2024',
    'August 24, 2024',
    'August 25, 2024',
    'August 27, 2024',
    'September 18, 2024',
    'September 24, 2024',
    'September 29, 2024',
    'October 03, 2024',
    'October 05, 2024',
    'October 06, 2024',
    'October 08, 2024',
    'October 18, 2024',
    'October 26, 2024',
    'November 25, 2024',
    'November 26, 2024',
    'December 03, 2024',
    'December 13, 2024',
    'December 25, 2024',
  ];

  static const List<String> birthDays = [
    'Tuesday',
    'Tuesday',
    'Saturday',
    'Friday',
    'Saturday',
    'Friday',
    'Friday',
    'Monday',
    'Saturday',
    'Tuesday',
    'Tuesday',
    'Sunday',
    'Sunday',
    'Friday',
    'Wednesday',
    'Sunday',
    'Wednesday',
    'Monday',
    'Saturday',
    'Wednesday',
    'Wednesday',
    'Wednesday',
    'Friday',
    'Friday',
    'Saturday',
    'Sunday',
    'Tuesday',
    'Wednesday',
    'Tuesday',
    'Sunday',
    'Thursday',
    'Saturday',
    'Sunday',
    'Tuesday',
    'Friday',
    'Saturday',
    'Monday',
    'Tuesday',
    'Tuesday',
    'Friday',
    'Wednesday',
  ];

  static const List<String> employeePics = [
    UflImages.pcjha,
    UflImages.userPic,
    UflImages.prithyul,
    UflImages.userPic,
    UflImages.ritik,
    UflImages.bansal,
    UflImages.userPic,
    UflImages.shailesh,
    UflImages.userPic,
    UflImages.pradeep,
    UflImages.userProfile,
    UflImages.userPic,
    UflImages.userPic,
    UflImages.sonal,
    UflImages.sudarshan,
    UflImages.userPic,
    UflImages.userPic,
    UflImages.pooja,
    UflImages.jaskaran,
    UflImages.userPic,
    UflImages.userPic,
    UflImages.amitraghav,
    UflImages.kapil,
    UflImages.userPic,
    UflImages.vinay,
    UflImages.aashish,
    UflImages.parul,
    UflImages.sharad,
    UflImages.userPic,
    UflImages.nitesh,
    UflImages.narender,
    UflImages.amitsingh,
    UflImages.userProfile,
    UflImages.userPic,
    UflImages.userProfile,
    UflImages.taufiq,
    UflImages.userPic,
    UflImages.rajeevjha,
    UflImages.userProfile,
    UflImages.upender,
    UflImages.userPic,
  ];
}